// Curated icon registry for feature cards. Every name here is verified to
// exist in @untitledui/icons — the agent picks from these names only, so a
// hallucinated icon can never break the build (unknown names fall back).
import type { FC } from "react";
import {
    Award01,
    BookOpen01,
    Briefcase01,
    Building01,
    Building02,
    Calendar,
    Camera01,
    Certificate01,
    CheckCircle,
    Clock,
    CreditCard01,
    Diamond01,
    Flash,
    Gift01,
    Globe01,
    GraduationHat01,
    Heart,
    Home01,
    Key01,
    Lightbulb01,
    Lock01,
    Mail01,
    MarkerPin01,
    MessageChatCircle,
    Moon01,
    MusicNote01,
    Palette,
    Phone,
    Scales01,
    Scissors01,
    Settings01,
    ShieldTick,
    Star01,
    Sun,
    ThumbsUp,
    Tool01,
    Tool02,
    Trophy01,
    Truck01,
    Umbrella01,
    Users01,
    Zap,
} from "@untitledui/icons";

export const ICONS: Record<string, FC<{ className?: string }>> = {
    "award": Award01,
    "book-open": BookOpen01,
    "briefcase": Briefcase01,
    "building": Building01,
    "storefront": Building02,
    "calendar": Calendar,
    "camera": Camera01,
    "certificate": Certificate01,
    "check-circle": CheckCircle,
    "clock": Clock,
    "credit-card": CreditCard01,
    "diamond": Diamond01,
    "flash": Flash,
    "gift": Gift01,
    "globe": Globe01,
    "graduation-hat": GraduationHat01,
    "heart": Heart,
    "home": Home01,
    "key": Key01,
    "lightbulb": Lightbulb01,
    "lock": Lock01,
    "mail": Mail01,
    "map-pin": MarkerPin01,
    "chat": MessageChatCircle,
    "moon": Moon01,
    "music": MusicNote01,
    "palette": Palette,
    "phone": Phone,
    "scales": Scales01,
    "scissors": Scissors01,
    "settings": Settings01,
    "shield-tick": ShieldTick,
    "star": Star01,
    "sun": Sun,
    "thumbs-up": ThumbsUp,
    "tool": Tool01,
    "wrench": Tool02,
    "trophy": Trophy01,
    "truck": Truck01,
    "umbrella": Umbrella01,
    "users": Users01,
    "zap": Zap,
};

/** Icon names the agent may use, for embedding in the generation prompt. */
export const ICON_NAMES = Object.keys(ICONS);

/** Unknown names degrade gracefully instead of crashing the build. */
export function getIcon(name: string): FC<{ className?: string }> {
    return ICONS[name] ?? CheckCircle;
}
